from flask import Blueprint, request, jsonify, send_file
import tempfile
import subprocess
from pathlib import Path
import os
import time
import shutil

video_routes = Blueprint('video_routes', __name__)

def create_manim_file(code, temp_dir):
    file_path = os.path.join(temp_dir, "scene.py")
    try:
        print("[INFO] Creating Manim code file...")
        with open(file_path, "w") as f:
            f.write(code)
        print("[SUCCESS] Manim code file created at:", file_path)
    except Exception as e:
        print("[ERROR] Failed to create Manim file:", str(e))
        raise e 
    return file_path

def generate_video(manim_file, temp_dir):
    try:
        print("[INFO] Starting video generation with Manim...")
        start_time = time.time()
        
        # Create media directory if it doesn't exist
        media_dir = os.path.join(temp_dir, "media", "videos", "scene", "1080p60")
        os.makedirs(media_dir, exist_ok=True)
        
        cmd = [
            "manim",
            "-pql",  # Fast rendering (use -pqh for high quality)
            "--media_dir", temp_dir,  # Specify media directory explicitly
            manim_file,
            "SquareToCircleToText"
        ]
        
        print("[DEBUG] Running command:", " ".join(cmd))
        
        # Run manim with full output capture
        result = subprocess.run(
            cmd,
            cwd=temp_dir,
            capture_output=True,
            text=True
        )
        
        print("[DEBUG] Manim stdout:", result.stdout)
        print("[DEBUG] Manim stderr:", result.stderr)
        
        if result.returncode != 0:
            print("[ERROR] Manim failed with stderr:")
            print(result.stderr)
            return None, f"Manim error: {result.stderr}"
        
        # Search for the video file
        print("[INFO] Looking for video file in:", media_dir)
        video_files = []
        for ext in ['.mp4', '.mov']:
            video_files.extend(list(Path(media_dir).glob(f"*{ext}")))
        
        if not video_files:
            # Try searching the entire temp directory as fallback
            print("[INFO] Searching entire temp directory for video files...")
            for ext in ['.mp4', '.mov']:
                video_files.extend(list(Path(temp_dir).rglob(f"*{ext}")))
        
        if not video_files:
            print("[ERROR] No video file found!")
            return None, "No video file generated by Manim."
        
        video_file = video_files[0]
        print("[SUCCESS] Video generated at:", video_file)
        
        # Copy to permanent storage
        permanent_path = os.path.join('/app/static/videos', f"render_{int(time.time())}.mp4")
        shutil.copy2(str(video_file), permanent_path)
        
        end_time = time.time()
        print(f"[INFO] Video generation took {end_time - start_time:.2f} seconds.")
        
        return permanent_path, None
        
    except Exception as e:
        print("[ERROR] Exception during video generation:", str(e))
        return None, str(e)

@video_routes.route('/generate-video', methods=['POST'])
def generate_video_route():
    try:
        print("[INFO] Received request to generate video...")
        data = request.json
        manim_code = data.get('code')
        
        if not manim_code:
            print("[ERROR] No Manim code provided in the request.")
            return jsonify({'error': 'No Manim code provided'}), 400
        
        # Create a unique temporary directory
        temp_dir = tempfile.mkdtemp(dir='/app/temp_renders')
        try:
            print("[INFO] Using temporary directory:", temp_dir)
            manim_file = create_manim_file(manim_code, temp_dir)
            video_path, error = generate_video(manim_file, temp_dir)
            
            if error:
                print("[ERROR] Video generation failed:", error)
                return jsonify({"error": error}), 500
            
            print("[INFO] Sending generated video to client...")
            return send_file(
                video_path,
                mimetype='video/mp4',
                as_attachment=True,
                download_name='animation.mp4'
            )
        finally:
            # Clean up temporary directory
            shutil.rmtree(temp_dir, ignore_errors=True)
            
    except Exception as e:
        print(f"[ERROR] Exception in generate-video route: {str(e)}")
        return jsonify({"error": str(e)}), 500